apiVersion: v1
kind: Service
metadata:
  name: {{ include "ferretdb.fullname" . }}
  labels:
    {{- include "ferretdb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.portHttp }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.portDebug }}
      targetPort: debug
      protocol: TCP
      name: debug
  selector:
    {{- include "ferretdb.selectorLabels" . | nindent 4 }}
