apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pgrest.fullname" . }}
  labels:
    {{- include "pgrest.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "pgrest.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pgrest.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pgrest.serviceAccountName" . }}
      {{- if .Values.podSecurityContext.enabled }}
      securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.podSecurityContext "context" $) | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- if .Values.securityContext.enabled }}
          securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.securityContext "context" $) | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
          {{- range $current_cm := .Values.extraConfigMaps }}
            - configMapRef:
              name: {{ $current_cm }}
          {{ end -}}
          {{- range $current_secret := .Values.extraSecrets }}
            - secretRef:
              name: {{ $current_secret }}
          {{ end -}}
          ports:
            - name: api
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            {{- if .Values.serviceAdmin.enabled }}
            - name: admin
              containerPort: {{ .Values.serviceAdmin.port }}
              protocol: TCP
            {{- end }}
          readinessProbe:
            {{- .Values.readinessProbe | toYaml | nindent 12 }}
          livenessProbe:
            {{- .Values.livenessProbe | toYaml | nindent 12 }}
          startupProbe:
            {{- .Values.startupProbe | toYaml | nindent 12 }}
          resources:
            {{- .Values.resources | toYaml | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
