apiVersion: v1
kind: Service
metadata:
  name: {{ include "pgrest.fullname" . }}
  labels:
    {{- include "pgrest.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "pgrest.selectorLabels" . | nindent 4 }}
